# Human-friendly value aliases for German Credit categorical codes
values:
  checking_status:            # Attribute1
    A11: "< 0 DM"
    A12: "0-200 DM"
    A13: ">= 200 DM / salary"
    A14: "no checking"
  credit_history:             # Attribute3
    A30: "no credits / all paid"
    A31: "all paid at this bank"
    A32: "paid till now"
    A33: "delay in past"
    A34: "critical/other existing"
  purpose:                     # Attribute4
    A40: "car (new)"
    A41: "car (used)"
    A42: "furniture/equipment"
    A43: "radio/TV"
    A44: "domestic appliances"
    A45: "repairs"
    A46: "education"
    A47: "vacation"
    A48: "retraining"
    A49: "business"
    A410: "other"
  savings:                     # Attribute6
    A61: "< 100 DM"
    A62: "100-500 DM"
    A63: "500-1000 DM"
    A64: ">= 1000 DM"
    A65: "unknown/no savings"
  employment_since:            # Attribute7
    A71: "unemployed"
    A72: "< 1 yr"
    A73: "1-4 yrs"
    A74: "4-7 yrs"
    A75: ">= 7 yrs"
  personal_status_sex:         # Attribute9
    A91: "male: divorced/sep"
    A92: "female: div/sep/married"
    A93: "male: single"
    A94: "male: married/widowed"
    A95: "female: single"
  other_debtors:               # Attribute10
    A101: "none"
    A102: "co-applicant"
    A103: "guarantor"
  property:                    # Attribute12
    A121: "real estate"
    A122: "bldg society/life ins."
    A123: "car/other"
    A124: "unknown/no property"
  other_installment_plans:     # Attribute14
    A141: "bank"
    A142: "stores"
    A143: "none"
  housing:                     # Attribute15
    A151: "rent"
    A152: "own"
    A153: "for free"
  job:                         # Attribute17
    A171: "unemployed/unskilled-nr"
    A172: "unskilled-resident"
    A173: "skilled employee/official"
    A174: "management/self-employed"
  telephone:                   # Attribute19
    A191: "none"
    A192: "yes, registered"
  foreign_worker:              # Attribute20
    A201: "yes"
    A202: "no"
