# Map CSV columns to canonical names used by the pipeline.
map:
  Attribute1:  checking_status
  Attribute2:  loan_term_months
  Attribute3:  credit_history
  Attribute4:  purpose
  Attribute5:  loan_amount
  Attribute6:  savings
  Attribute7:  employment_since
  Attribute8:  installment_rate_pct
  Attribute9:  personal_status_sex
  Attribute10: other_debtors
  Attribute11: residence_since
  Attribute12: property
  Attribute13: age
  Attribute14: other_installment_plans
  Attribute15: housing
  Attribute16: existing_credits
  Attribute17: job
  Attribute18: dependents
  Attribute19: telephone
  Attribute20: foreign_worker
  class:       bad_within_horizon   # 1/2 → 0/1 mapping happens in loader
