mode: "learned"
adapter: "universal"

data_source: "ucimlrepo"
uci_id: 144

# Optional remap/aliases (comment out if not present)
# column_map: "configs/column_map_credit.yaml"
# domain_pack: "data/aliases/credit.yaml"

output_dir: "outputs/credit_run"
seed: 242
device: "cuda"

task: "credit_portfolio"
months: 18
start_date: "2019-01-31"
init_customers: 100000
base_new: 120

training_profile: thorough

privacy_enabled: false
dp_max_grad_norm: 1.0
dp_noise_multiplier: 0.0
dp_delta: 1e-5

# Treat small-cardinality ints as categorical; set columns explicitly for German
cont_cols: ["Attribute2","Attribute5","Attribute13"]             # Duration, Credit amount, Age
cat_cols:  ["Attribute1","Attribute3","Attribute4","Attribute6",
            "Attribute7","Attribute8","Attribute9","Attribute10",
            "Attribute11","Attribute12","Attribute14","Attribute15",
            "Attribute16","Attribute17","Attribute19","Attribute20"]

# Per-column transforms (handled by your schema utils)
transforms:
  Attribute5: log1p      # heavy tail credit amount

pdcal:
  mode: auto            # auto (recommended) | fixed
  horizon_months: 12    # PD horizon -> simulator converts to monthly hazard
  max_cont: 8           # max numeric features to use (auto mode)
  max_cat: 8            # max categorical features to use (auto mode)
  max_cat_levels: 30    # drop cats with too many levels (avoids huge one-hots)
  include: []           # optional regexes to force-include (e.g., ["^age$", "^income$"])
  exclude: ["^id$", "^index$", "^name$"]  # regexes to exclude junk cols
  
shock_enabled: false

# >>> SHOCKS <<<
shock:
  corr_shrink: 0.25
  # either list of triples:
  corr_pairs:
    - [income, loan_amount, 0.6]
    - [age, loan_amount, -0.2]
  # or as a dict with string keys "(col_i,col_j)": rho
  # corr_pairs:
  #   "(income,loan_amount)": 0.6

  cont_mu_shift:
    income: 1000

  cont_scale:
    loan_amount: 1.1

  residual_scale: 1.2

  # categorical biases: use your category VALUES (e.g., German A-codes)
  cat_logit_bias:
    purpose:
      A40: 0.5     # tilt towards "car (new)"
      A45: -0.2    # tilt away from "repairs"
